/** Postgres schema. Idempotent: safe to run on every cold start. */
export const SCHEMA = `
CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  phone         TEXT,
  password_hash TEXT,            -- development only, Neon Auth holds credentials in production
  auth_id       TEXT,            -- neon_auth."user".id
  name          TEXT NOT NULL,
  role          TEXT NOT NULL CHECK(role IN ('customer','operator','admin')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS operators (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER NOT NULL UNIQUE REFERENCES users(id),
  company_name  TEXT NOT NULL,
  certificate   TEXT,
  status        TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','suspended')),
  -- Contact preferences
  contact_method TEXT NOT NULL DEFAULT 'email' CHECK(contact_method IN ('email','text','both')),
  contact_email  TEXT,
  contact_phone  TEXT,
  -- Operator profile for matching
  safety_rating  TEXT,
  fleet_types    TEXT,   -- JSON array: ["light","mid","heavy","ultra_long"]
  markets        TEXT,   -- JSON array: ["hi_inter","mainland_hi","west","east",...]
  range_max_nm   INTEGER,
  hi_capable     INTEGER NOT NULL DEFAULT 0,
  transoceanic   INTEGER NOT NULL DEFAULT 0,
  notes          TEXT,
  -- Stripe Connect payout account
  stripe_account_id        TEXT,
  stripe_charges_enabled   INTEGER NOT NULL DEFAULT 0,
  stripe_payouts_enabled   INTEGER NOT NULL DEFAULT 0,
  stripe_details_submitted INTEGER NOT NULL DEFAULT 0,
  platform_fee_bps         INTEGER,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS aircraft (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id   INTEGER NOT NULL REFERENCES operators(id),
  tail_number   TEXT NOT NULL,
  type          TEXT NOT NULL,
  capacity      INTEGER NOT NULL,
  range_nm      INTEGER,
  year          INTEGER,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS booking_requests (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     INTEGER NOT NULL REFERENCES users(id),
  status          TEXT NOT NULL DEFAULT 'open'
                  CHECK(status IN ('open','quoted','booked','cancelled','completed')),
  passenger_count INTEGER NOT NULL DEFAULT 1,
  notes           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS booking_legs (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id      INTEGER NOT NULL REFERENCES booking_requests(id) ON DELETE CASCADE,
  leg_order       INTEGER NOT NULL,
  origin_code     TEXT NOT NULL,
  origin_name     TEXT,
  dest_code       TEXT NOT NULL,
  dest_name       TEXT,
  departure_date  TEXT NOT NULL,
  departure_time  TEXT,
  UNIQUE(request_id, leg_order)
);

CREATE TABLE IF NOT EXISTS quotes (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id    INTEGER NOT NULL REFERENCES booking_requests(id),
  operator_id   INTEGER NOT NULL REFERENCES operators(id),
  aircraft_id   INTEGER REFERENCES aircraft(id),
  price_cents   BIGINT NOT NULL,
  currency      TEXT NOT NULL DEFAULT 'USD',
  message       TEXT,
  status        TEXT NOT NULL DEFAULT 'pending'
                CHECK(status IN ('pending','accepted','rejected','withdrawn')),
  valid_until   TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Outreach log: tracks every RFQ dispatched to an operator
CREATE TABLE IF NOT EXISTS outreach_log (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id    INTEGER NOT NULL REFERENCES booking_requests(id),
  operator_id   INTEGER NOT NULL REFERENCES operators(id),
  method        TEXT NOT NULL CHECK(method IN ('email','text','both','pending')),
  match_score   INTEGER NOT NULL DEFAULT 0,
  rfq_subject   TEXT,
  rfq_body      TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'sent' CHECK(status IN ('queued','sent','delivered','failed','responded')),
  sent_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  responded_at  TIMESTAMPTZ,
  UNIQUE(request_id, operator_id)
);

-- Discovered operators: found via FAA registry scrape, pending outreach
CREATE TABLE IF NOT EXISTS discovered_operators (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name       TEXT NOT NULL,
  dba_name           TEXT,
  certificate_number TEXT UNIQUE,
  contact_email      TEXT,
  phone              TEXT,
  address            TEXT,
  city               TEXT,
  state              TEXT,
  zip                TEXT,
  status             TEXT NOT NULL DEFAULT 'new'
                     CHECK(status IN ('new','no_email','emailed','registered','opted_out','bounced')),
  source             TEXT NOT NULL DEFAULT 'faa_registry',
  discovered_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  emailed_at         TIMESTAMPTZ,
  invite_resend_id   TEXT,
  notes              TEXT
);

-- Payments: one row per checkout attempt for an accepted quote.
-- Funds are collected by the platform and routed to the operator's
-- Stripe Connect account, minus the platform fee.
CREATE TABLE IF NOT EXISTS payments (
  id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id                 INTEGER NOT NULL REFERENCES booking_requests(id),
  quote_id                   INTEGER NOT NULL REFERENCES quotes(id),
  customer_id                INTEGER NOT NULL REFERENCES users(id),
  operator_id                INTEGER NOT NULL REFERENCES operators(id),
  amount_cents               BIGINT NOT NULL,
  platform_fee_cents         BIGINT NOT NULL,
  operator_payout_cents      BIGINT NOT NULL,
  refunded_cents             BIGINT NOT NULL DEFAULT 0,
  currency                   TEXT NOT NULL DEFAULT 'USD',
  status                     TEXT NOT NULL DEFAULT 'pending'
                             CHECK(status IN ('pending','processing','succeeded','failed','canceled','refunded','partially_refunded')),
  provider                   TEXT NOT NULL DEFAULT 'stripe' CHECK(provider IN ('stripe','stub')),
  stripe_checkout_session_id TEXT UNIQUE,
  stripe_payment_intent_id   TEXT UNIQUE,
  stripe_destination_account TEXT,
  checkout_url               TEXT,
  failure_reason             TEXT,
  dispute_status             TEXT,
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  paid_at                    TIMESTAMPTZ
);

-- Refund ledger. refunded_cents on payments is the running total.
CREATE TABLE IF NOT EXISTS refunds (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id       INTEGER NOT NULL REFERENCES payments(id),
  amount_cents     BIGINT NOT NULL,
  reason           TEXT,
  stripe_refund_id TEXT UNIQUE,
  initiated_by     INTEGER REFERENCES users(id),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Processed Stripe webhook events, for idempotency.
CREATE TABLE IF NOT EXISTS payment_events (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_event_id TEXT NOT NULL UNIQUE,
  type            TEXT NOT NULL,
  received_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at    TIMESTAMPTZ
);

-- Private trip-sheet links an operator shares with their own staff
-- (dispatch, crew, catering). Anyone holding the token can view the sheet
-- until it is revoked or expires.
CREATE TABLE IF NOT EXISTS trip_shares (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id  INTEGER NOT NULL REFERENCES booking_requests(id),
  operator_id INTEGER NOT NULL REFERENCES operators(id),
  token       TEXT NOT NULL UNIQUE,
  created_by  INTEGER REFERENCES users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at  TIMESTAMPTZ NOT NULL,
  revoked_at  TIMESTAMPTZ
);

-- Operator staff who receive automatic alerts (they do not log in).
CREATE TABLE IF NOT EXISTS operator_staff (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id       INTEGER NOT NULL REFERENCES operators(id),
  name              TEXT NOT NULL,
  role              TEXT,
  email             TEXT,
  phone             TEXT,
  notify_email      INTEGER NOT NULL DEFAULT 1,
  notify_sms        INTEGER NOT NULL DEFAULT 0,
  on_new_request    INTEGER NOT NULL DEFAULT 0,
  on_booking        INTEGER NOT NULL DEFAULT 1,
  on_cancellation   INTEGER NOT NULL DEFAULT 1,
  active            INTEGER NOT NULL DEFAULT 1,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Every alert sent to a staff member. The unique key makes alerts
-- idempotent: a retried webhook cannot notify the same person twice.
CREATE TABLE IF NOT EXISTS staff_notifications (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id    INTEGER NOT NULL REFERENCES operator_staff(id) ON DELETE CASCADE,
  event_key   TEXT NOT NULL,
  channel     TEXT NOT NULL CHECK(channel IN ('email','sms')),
  status      TEXT NOT NULL CHECK(status IN ('sent','failed')),
  error       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(staff_id, event_key, channel)
);

-- Private, revocable link to an operator's live company board (for staff
-- without logins, e.g. a screen in dispatch).
CREATE TABLE IF NOT EXISTS operator_boards (
  operator_id INTEGER PRIMARY KEY REFERENCES operators(id),
  token       TEXT NOT NULL UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_booking_requests_customer ON booking_requests(customer_id);
CREATE INDEX IF NOT EXISTS idx_booking_requests_status ON booking_requests(status);
CREATE INDEX IF NOT EXISTS idx_booking_legs_request ON booking_legs(request_id);
CREATE INDEX IF NOT EXISTS idx_quotes_request ON quotes(request_id);
CREATE INDEX IF NOT EXISTS idx_quotes_operator ON quotes(operator_id);
CREATE INDEX IF NOT EXISTS idx_aircraft_operator ON aircraft(operator_id);
CREATE INDEX IF NOT EXISTS idx_outreach_request ON outreach_log(request_id);
CREATE INDEX IF NOT EXISTS idx_outreach_operator ON outreach_log(operator_id);
CREATE INDEX IF NOT EXISTS idx_operators_status ON operators(status);
CREATE INDEX IF NOT EXISTS idx_discovered_status ON discovered_operators(status);
CREATE INDEX IF NOT EXISTS idx_discovered_cert ON discovered_operators(certificate_number);
CREATE INDEX IF NOT EXISTS idx_discovered_state ON discovered_operators(state);
CREATE INDEX IF NOT EXISTS idx_payments_request ON payments(request_id);
CREATE INDEX IF NOT EXISTS idx_payments_quote ON payments(quote_id);
CREATE INDEX IF NOT EXISTS idx_payments_operator ON payments(operator_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_refunds_payment ON refunds(payment_id);
CREATE INDEX IF NOT EXISTS idx_trip_shares_request ON trip_shares(request_id, operator_id);
CREATE INDEX IF NOT EXISTS idx_operator_staff_operator ON operator_staff(operator_id);

-- Neon Auth: link app profiles to neon_auth users. Existing databases predate these.
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_id TEXT;
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_auth_id ON users(auth_id);
`;
